"""empty message

Revision ID: bd9cbf029d80
Revises: 645e9cf2d7f8
Create Date: 2023-06-16 14:45:09.747637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9cbf029d80'
down_revision = '645e9cf2d7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homework_name', sa.String(length=500), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=130),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=130),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_column('homework_name')

    # ### end Alembic commands ###
