"""empty message

Revision ID: 5a05bfae1221
Revises: 149155bb2b06
Create Date: 2023-06-15 09:05:01.431544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a05bfae1221'
down_revision = '149155bb2b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homework_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homework_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('homework_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('homework_id')

    # ### end Alembic commands ###
