"""empty message

Revision ID: e39ebcd4c1fd
Revises: 7366bb317e2c
Create Date: 2023-06-13 15:15:14.887478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39ebcd4c1fd'
down_revision = '7366bb317e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('superpower',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('homework_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('homework_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('superpower',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
